# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYhpnGCyNGCG0kVm1bVpfrvBOum0N0pF

# Task 2: Integrated Mutation and Methylation Classification
## Overview
This script integrates mutation and methylation data to build a classifier for cancer subtypes.
It includes:
- Data loading for mutation and methylation datasets
- Feature engineering for mutations and methylation
- Integration of features
- Model training with RandomForest and XGBoost
- Evaluation with metrics and confusion matrix
- Visualizations for mutation and methylation distributions
"""

# Install required libraries
!pip install pandas numpy scikit-learn matplotlib xgboost cudf-cu12 --extra-index-url=https://pypi.nvidia.com

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, f_classif, VarianceThreshold
from sklearn.metrics import f1_score, precision_score, recall_score, ConfusionMatrixDisplay
import xgboost as xgb
from xgboost import XGBClassifier, DMatrix
import cudf
import os
import torch
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('task2_log.txt'),
        logging.StreamHandler()
    ]
)

# Check GPU availability
if torch.cuda.is_available():
    logging.info(f"GPU is available: {torch.cuda.get_device_name(0)}")
else:
    logging.error("GPU not available. Please enable GPU runtime in Colab.")
    raise SystemExit("GPU not available.")

# Set working directory
os.chdir('/content/work')

# Generate and Save Confusion Matrix
os.makedirs('out', exist_ok=True)
output_dir = 'out'
os.makedirs(output_dir, exist_ok=True)

"""## Phase 1: Data Loading
Loads mutation, methylation, and feature data using GPU-accelerated CSV reading.
Checks for missing values and validates data integrity.
"""

logging.info("Loading data for Task 2...")
try:
    train_muts = cudf.read_csv('train_muts_data.csv').to_pandas()
    test_muts = cudf.read_csv('test_muts_data.csv').to_pandas()
    train_feats = cudf.read_csv('train_feats.csv').to_pandas()
    test_feats = cudf.read_csv('test_feats.csv').to_pandas()
    train_meth = cudf.read_csv('train_meth_data.csv').to_pandas()
    test_meth = cudf.read_csv('test_meth_data.csv').to_pandas()
    genes_100 = cudf.read_csv('100_genes.csv').to_pandas()
except FileNotFoundError as e:
    logging.error(f"File not found: {e}")
    raise SystemExit(f"Error: File not found: {e}")

# Check for missing values
logging.info("Checking for missing values...")
for df, name in [(train_muts, 'train_muts'), (test_muts, 'test_muts'), (train_feats, 'train_feats'),
                (test_feats, 'test_feats'), (train_meth, 'train_meth'), (test_meth, 'test_meth')]:
    missing = df.isnull().sum().sum()
    logging.info(f"{name}: {missing} missing values")
    if missing > 0:
        logging.warning(f"{name} contains {missing} missing values")

"""## Phase 2: Feature Engineering (Mutations)
Generates mutation features:
- Total mutations per patient
- Mutations by variant classification
- Gene-specific mutations
- Mutation types (Transition, Transversion, etc.)
- Normalized mutation rates
"""

logging.info("Creating mutation features...")

# Total mutations per case
train_total_muts = train_muts.groupby('case_id').size().reset_index(name='Total_Mutations')
test_total_muts = test_muts.groupby('case_id').size().reset_index(name='Total_Mutations')

# Variant classification counts per case
train_var_counts = train_muts.groupby(['case_id', 'Variant_Classification']).size().unstack(fill_value=0)
train_var_counts.columns = [f'Mutations_{col}' for col in train_var_counts.columns]

test_var_counts = test_muts.groupby(['case_id', 'Variant_Classification']).size().unstack(fill_value=0)
test_var_counts.columns = [f'Mutations_{col}' for col in test_var_counts.columns]

# Mutations per gene and variant classification
train_gene_var = train_muts.groupby(['case_id', 'Gene_name', 'Variant_Classification']).size().unstack(level=[1, 2], fill_value=0)
train_gene_var.columns = [f'Mutations_in_{gene}_{var}' for gene, var in train_gene_var.columns]

test_gene_var = test_muts.groupby(['case_id', 'Gene_name', 'Variant_Classification']).size().unstack(level=[1, 2], fill_value=0)
test_gene_var.columns = [f'Mutations_in_{gene}_{var}' for gene, var in test_gene_var.columns]

# Mutation type classifier
def classify_mutation(row):
    ref, tumor = row['Reference_Allele'], row['Tumor_Seq_Allele1']
    if len(ref) == len(tumor) == 1:
        transitions = {('A', 'G'), ('G', 'A'), ('C', 'T'), ('T', 'C')}
        return 'Transition' if (ref, tumor) in transitions else 'Transversion'
    elif len(ref) > len(tumor):
        return 'Deletion'
    elif len(ref) < len(tumor):
        return 'Insertion'
    return 'Other'

logging.info("Classifying mutation types...")
train_muts['Mut_Type'] = train_muts.apply(classify_mutation, axis=1)
test_muts['Mut_Type'] = test_muts.apply(classify_mutation, axis=1)

# Check distribution of mutation types
logging.info("Mutation type distribution in train_muts:")
mut_type_dist_train = train_muts['Mut_Type'].value_counts()
logging.info(mut_type_dist_train.to_string())
other_prop_train = mut_type_dist_train.get('Other', 0) / len(train_muts)
if other_prop_train > 0.1:
    logging.warning(f"High proportion of 'Other' mutations in train_muts: {other_prop_train:.2%}")

logging.info("Mutation type distribution in test_muts:")
mut_type_dist_test = test_muts['Mut_Type'].value_counts()
logging.info(mut_type_dist_test.to_string())
other_prop_test = mut_type_dist_test.get('Other', 0) / len(test_muts)
if other_prop_test > 0.1:
    logging.warning(f"High proportion of 'Other' mutations in test_muts: {other_prop_test:.2%}")

# Group by mutation types
train_mut_types = train_muts.groupby(['case_id', 'Mut_Type']).size().unstack(fill_value=0)
train_mut_types.columns = [f'Mutations_{col}' for col in train_mut_types.columns]

test_mut_types = test_muts.groupby(['case_id', 'Mut_Type']).size().unstack(fill_value=0)
test_mut_types.columns = [f'Mutations_{col}' for col in test_mut_types.columns]

# Calculate gene sequence lengths
genes_100['Length'] = genes_100['Sequence'].str.len()

# Normalized mutations for train set
train_norm_muts = train_muts.groupby(['case_id', 'Gene_name']).size().reset_index(name='Count')
train_norm_muts = train_norm_muts.merge(genes_100[['gene', 'Length']], left_on='Gene_name', right_on='gene', how='left')
train_norm_muts['Norm_Mutations'] = train_norm_muts['Count'] / train_norm_muts['Length']
train_norm_muts = train_norm_muts.pivot(index='case_id', columns='Gene_name', values='Norm_Mutations').fillna(0)
train_norm_muts.columns = [f'Norm_Mutations_in_{col}' for col in train_norm_muts.columns]

# Normalized mutations for test set - FIXED HERE
test_norm_muts = test_muts.groupby(['case_id', 'Gene_name']).size().reset_index(name='Count')
test_norm_muts = test_norm_muts.merge(genes_100[['gene', 'Length']], left_on='Gene_name', right_on='gene', how='left')
test_norm_muts['Norm_Mutations'] = test_norm_muts['Count'] / test_norm_muts['Length']  # use test_norm_muts Length here
test_norm_muts = test_norm_muts.pivot(index='case_id', columns='Gene_name', values='Norm_Mutations').fillna(0)
test_norm_muts.columns = [f'Norm_Mutations_in_{col}' for col in test_norm_muts.columns]

# Join all features for train and test
train_features = train_total_muts.set_index('case_id').join([
    train_var_counts, train_gene_var, train_mut_types, train_norm_muts
]).reset_index()

test_features = test_total_muts.set_index('case_id').join([
    test_var_counts, test_gene_var, test_mut_types, test_norm_muts
]).reset_index()

"""## Phase 3: Feature Engineering (Methylation)
Generates methylation features:
- Average methylation per gene
- Standard deviation of methylation
- Proportion of hypermethylated sites (beta_val > 0.7)
- Mutation-methylation interaction
"""

logging.info("Creating methylation features...")
train_meth_avg = train_meth.groupby(['case_id', 'matching_genes'])['beta_val'].mean().unstack(fill_value=0)
train_meth_avg.columns = [f'Meth_Avg_{col}' for col in train_meth_avg.columns]
test_meth_avg = test_meth.groupby(['case_id', 'matching_genes'])['beta_val'].mean().unstack(fill_value=0)
test_meth_avg.columns = [f'Meth_Avg_{col}' for col in test_meth_avg.columns]
train_meth_std = train_meth.groupby(['case_id', 'matching_genes'])['beta_val'].std().unstack(fill_value=0)
train_meth_std.columns = [f'Meth_Std_{col}' for col in train_meth_std.columns]
test_meth_std = test_meth.groupby(['case_id', 'matching_genes'])['beta_val'].std().unstack(fill_value=0)
test_meth_std.columns = [f'Meth_Std_{col}' for col in test_meth_std.columns]
train_meth_high = train_meth[train_meth['beta_val'] > 0.7].groupby(['case_id', 'matching_genes']).size().unstack(fill_value=0)
train_meth_high = train_meth_high.div(train_meth.groupby(['case_id', 'matching_genes']).size().unstack(fill_value=1)).fillna(0)
train_meth_high.columns = [f'Meth_High_Prop_{col}' for col in train_meth_high.columns]
test_meth_high = test_meth[test_meth['beta_val'] > 0.7].groupby(['case_id', 'matching_genes']).size().unstack(fill_value=0)
test_meth_high = test_meth_high.div(test_meth.groupby(['case_id', 'matching_genes']).size().unstack(fill_value=1)).fillna(0)
test_meth_high.columns = [f'Meth_High_Prop_{col}' for col in test_meth_high.columns]
train_interaction = train_muts.merge(train_meth[train_meth['beta_val'] > 0.7], left_on=['case_id', 'Gene_name'], right_on=['case_id', 'matching_genes'], how='inner')
train_interaction = train_interaction.groupby('case_id').size().reset_index(name='Mut_Meth_Interaction')
test_interaction = test_muts.merge(test_meth[test_meth['beta_val'] > 0.7], left_on=['case_id', 'Gene_name'], right_on=['case_id', 'matching_genes'], how='inner')
test_interaction = test_interaction.groupby('case_id').size().reset_index(name='Mut_Meth_Interaction')
train_interaction = train_interaction.set_index('case_id').reindex(train_features['case_id']).fillna(0).reset_index()
test_interaction = test_interaction.set_index('case_id').reindex(test_features['case_id']).fillna(0).reset_index()

# Combine features
train_combined = train_features.set_index('case_id').join([train_meth_avg, train_meth_std, train_meth_high, train_interaction.set_index('case_id')]).reset_index()
test_combined = test_features.set_index('case_id').join([test_meth_avg, test_meth_std, test_meth_high, test_interaction.set_index('case_id')]).reset_index()
train_combined.to_csv('out/train_combined.csv', index=False)
test_combined.to_csv('out/test_combined.csv', index=False)
logging.info("Combined features saved as 'train_combined.csv' and 'test_combined.csv'.")

"""## Phase 4: Visualizations
Creates visualizations for:
- Mutation distribution by variant type (train + test)
- Top 20 genes by mutation count (train + test)
- Methylation distribution by gene (train only)
"""

logging.info("Creating visualizations for Task 2...")
# Mutation Distribution by Variant Type (Train + Test)
try:
    all_muts = pd.concat([train_muts, test_muts], ignore_index=True)
    grouped_data = all_muts.groupby('Variant_Classification').size()
    plt.figure(figsize=(12, 6))
    bars = grouped_data.plot(kind='bar')
    plt.xlabel('Variant Classification')
    plt.ylabel('Number of Mutations')
    plt.title('Mutation Distribution by Variant Type (Train + Test Data)')
    for bar in bars.patches:
        plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f'{int(bar.get_height())}',
                ha='center', va='bottom')
    plt.tight_layout()
    plt.savefig('out/mutation_distribution_by_variant.png', dpi=300)
    logging.info("Saved mutation_distribution_by_variant.png")
    plt.show()
    plt.close()
except Exception as e:
    logging.error(f"Failed to create variant type visualization: {e}")

# Top 20 Genes by Mutation Count (Train + Test)
try:
    gene_totals = all_muts.groupby('Gene_name').size().sort_values(ascending=False).head(20)
    plt.figure(figsize=(12, 6))
    bars = gene_totals.plot(kind='bar')
    plt.xlabel('Gene')
    plt.ylabel('Number of Mutations')
    plt.title('Top 20 Genes by Mutation Count (Train + Test Data)')
    for bar in bars.patches:
        plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f'{int(bar.get_height())}',
                ha='center', va='bottom')
    plt.tight_layout()
    plt.savefig('out/mutation_distribution_by_gene.png', dpi=300)
    logging.info("Saved mutation_distribution_by_gene.png")
    plt.show()
    plt.close()
except Exception as e:
    logging.error(f"Failed to create gene mutation visualization: {e}")

# Methylation Distribution by Gene (Train Only)
try:
    meth_avg = train_meth.groupby('matching_genes')['beta_val'].mean().sort_values(ascending=False).head(20)
    plt.figure(figsize=(12, 6))
    bars = meth_avg.plot(kind='bar')
    plt.xlabel('Gene')
    plt.ylabel('Average Beta Value')
    plt.title('Top 20 Genes by Average Methylation (Train Data)')
    for bar in bars.patches:
        plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f'{bar.get_height():.2f}',
                ha='center', va='bottom')
    plt.tight_layout()
    plt.savefig('out/methylation_distribution_by_gene.png', dpi=300)
    logging.info("Saved methylation_distribution_by_gene.png")
    plt.show()
    plt.close()
except Exception as e:
    logging.error(f"Failed to create methylation visualization: {e}")

"""## Phase 5: Model Training and Evaluation
Trains classifiers using:
- Feature selection (VarianceThreshold, SelectKBest)
- RandomForest and XGBoost with GridSearchCV
- Validation on 20% stratified split
- Comparison with baseline metrics
"""

logging.info("Training Task 2 classifier...")
try:
    y_train = train_feats['Label'].astype(int) - 1
    X_train_combined = train_combined.drop(columns=['case_id']).fillna(0)
    X_test_combined = test_combined.drop(columns=['case_id']).fillna(0)
    X_test_combined = X_test_combined.reindex(columns=X_train_combined.columns, fill_value=0)
except Exception as e:
    logging.error(f"Error preparing data for training: {e}")
    raise Exception(f"Data preparation failed: {e}")

# Feature selection
logging.info("Performing feature selection...")
try:
    variance_threshold = VarianceThreshold(threshold=0)
    X_train_combined_var = variance_threshold.fit_transform(X_train_combined)
    X_test_combined_var = variance_threshold.transform(X_test_combined)
    selector = SelectKBest(score_func=f_classif, k=100)
    X_train_combined_selected = selector.fit_transform(X_train_combined_var, y_train)
    X_test_combined_selected = selector.transform(X_test_combined_var)
except Exception as e:
    logging.error(f"Error during feature selection: {e}")
    raise Exception(f"Feature selection failed: {e}")

# Split data
logging.info("Splitting data into train/validation sets...")
X_train_split, X_val, y_train_split, y_val = train_test_split(
    X_train_combined_selected, y_train, test_size=0.2, stratify=y_train, random_state=42)

# Classifiers
classifiers = {
    'RandomForest': RandomForestClassifier(random_state=42, n_jobs=-1),
    'XGBoost': XGBClassifier(tree_method='hist', device='cuda', random_state=42)
}

best_classifier = None
best_score = 0
best_name = None
metrics_comparison = []

# Train and evaluate
logging.info("Training and evaluating classifiers...")
for name, classifier in classifiers.items():
    try:
        param_grid = {
            'RandomForest': {'n_estimators': [100, 200, 300], 'max_depth': [3, 5, 7], 'min_samples_split': [2, 5]},
            'XGBoost': {'max_depth': [3, 5, 7], 'learning_rate': [0.01, 0.1, 0.3], 'n_estimators': [100, 200, 300]}
        }[name]
        grid_search = GridSearchCV(classifier, param_grid, cv=5, scoring='f1_weighted', n_jobs=-1)
        grid_search.fit(X_train_split, y_train_split)
        y_val_pred = grid_search.predict(X_val)
        error = (y_val_pred != y_val).mean()
        f1 = f1_score(y_val, y_val_pred, average='weighted')
        precision = precision_score(y_val, y_val_pred, average='weighted')
        recall = recall_score(y_val, y_val_pred, average='weighted')
        metrics_comparison.append({
            'Model': name,
            'F1-Score': f1,
            'Precision': precision,
            'Recall': recall,
            'Error Rate': error
        })
        logging.info(f"{name} Results:")
        logging.info(f"Validation Error: {error:.4f}, F1-Score: {f1:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
        if f1 > best_score:
            best_score = f1
            best_classifier = grid_search.best_estimator_
            best_name = name
    except Exception as e:
        logging.error(f"Error training {name}: {e}")
        continue

# Display metrics
try:
    metrics_df = pd.DataFrame(metrics_comparison)
    logging.info("\nModel Performance Comparison:")
    logging.info("Expected baseline (Task 1): F1-Score: 0.658, Precision: 0.676, Recall: 0.664")
    logging.info("\nActual performance (Task 2):")
    logging.info(metrics_df.to_string(index=False))
except Exception as e:
    logging.error(f"Error displaying metrics: {e}")

# Retrain best model
logging.info("Retraining best model...")
if best_name == 'XGBoost':
    try:
        dtrain = xgb.DMatrix(X_train_combined_selected, label=y_train)
        dval = xgb.DMatrix(X_val, label=y_val)
        dtest = xgb.DMatrix(X_test_combined_selected)
        params = best_classifier.get_xgb_params()
        params.update({'tree_method': 'hist', 'device': 'cuda'})
        xgb_model = xgb.train(
            params, dtrain, num_boost_round=1000, evals=[(dval, "validation")],
            early_stopping_rounds=10, verbose_eval=False)
        y_test_pred = xgb_model.predict(dtest)
        y_test_pred = (y_test_pred > 0.5).astype(int) + 1
    except Exception as e:
        logging.error(f"Error retraining XGBoost: {e}")
        raise Exception(f"XGBoost retraining failed: {e}")
else:
    try:
        best_classifier.fit(X_train_combined_selected, y_train)
        y_test_pred = best_classifier.predict(X_test_combined_selected) + 1
    except Exception as e:
        logging.error(f"Error retraining RandomForest: {e}")
        raise Exception(f"RandomForest retraining failed: {e}")

# Save predictions
try:
    pd.DataFrame({'id_case': test_combined['case_id'], 'label_predict': y_test_pred}).to_csv('out/task2_predictions.csv', index=False)
    logging.info("Saved task2_predictions.csv")
except Exception as e:
    logging.error(f"Error saving predictions: {e}")
    raise Exception(f"Prediction saving failed: {e}")

# Confusion matrix
logging.info("Generating confusion matrix...")
try:
    plt.figure(figsize=(8, 6))
    disp = ConfusionMatrixDisplay.from_predictions(y_val, best_classifier.predict(X_val), labels=[0, 1], display_labels=['HNSC', 'LUSC'], cmap='Blues')
    plt.title('Task 2: Integrated Classification\nConfusion Matrix')
    plt.tight_layout()
    plt.savefig('out/confusion_matrix_task2.png', dpi=300)
    plt.show()
    logging.info("Saved confusion_matrix_task2.png")
    plt.close()
except Exception as e:
    logging.error(f"Failed to save confusion matrix: {e}")

logging.info("Task 2 completed. Outputs saved to 'out' directory.")
print("Task 2 completed. Outputs saved to 'out' directory.")